### ISSUE TITLE
also set CUDA_DEVICE_ORDER

### ISSUE THREAD

**Issue by yaroslavvb** [bamos/setGPU#1]
Nice util!

I've been been [parsing](https://github.com/yaroslavvb/stuff/blob/master/notebook_util.py#L46) text output of `nvidia-smi` but this looks cleaner.

Since gpustat uses `nvidia-smi` under the covers, it will have the same problem with CUDA_DEVICE_ORDER -- `nvidia-smi` could say that, say, GPU 0 is available, but you have to do `CUDA_VISIBLE_DEVICES=1` to use that GPU, see https://github.com/tensorflow/tensorflow/issues/152#issuecomment-273542782 for discussion.

The solution is to always set CUDA_DEVICE_ORDER=PCI_BUS_ID

**Comment by bamos** [comment]
How embarrassing! I made a bad last-minute modification to the code before uploading it here without checking it. The latest version should be working well.
