### ISSUE TITLE
Wait interval before run next task?

### ISSUE THREAD

**Issue by mrgloom** [bamos/setGPU#3]
What is recommended wait interval before run next task? seems like setGPU fails if run python scripts near simultaneously.

Also what packages can be used to queue tasks if all GPUs are busy?

**Comment by bamos** [comment]
I usually just add a sleep for 5-10 seconds if I'm launching a lot of scripts.

You can use a fork of this https://github.com/riceric22/waitGPU by @riceric22 for queuing tasks if the GPUs are busy.
